### ISSUE TITLE
DeathShovel breaks shovel on update v47

### ISSUE THREAD

**Issue by kronflux** [Ccode-lang/DeathShovel#2]
I'm not entirely sure what the cause is, nor do I have the skills to debug unity/harmony/bepinex mods, but what happens is when you click to swing the shovel, it gets stuck in the "charged" state where it's ready to hit something, and you can no longer interact with anything, not even drop the shovel

**Comment by Ccode-lang** [comment]
Sorry didn't see this before. I did fix this at one point but v47 support is about to be dropped.
